language: julia

os:
  - linux
dist: xenial
addons:
  apt:
    packages:
      python3-sklearn

julia:
  - 1.0
  - 1.2
  - nightly

notifications:
  email: false

codecov: true

matrix:
    allow_failures:
        - julia: nightly


jobs:
  include:
    - stage: "Documentation"
      julia: 1.2
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.add(PackageSpec(url="https://github.com/tjjarvinen/PotentialCalculation.jl"))'
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));'
        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
