language: julia

os:
  - linux
dist: xenial

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

codecov: true

matrix:
    allow_failures:
        - julia: nightly

before_install:
  - sudo apt-get install python3-sklearn

jobs:
  include:
    - stage: "Documentation"
      julia: 1.1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip
